### ISSUE TITLE
[META] Roadmap 2.x

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/replicado#224]
- [ ] Injetar código da unidade por env e não por parâmetro #219
-  [ ] Método docentes($codundclgi) será removido em favor de listarDocentes($codset)
- [ ] phpunit: Verificar se existe annotation
- [ ] phpunit: Verificar se há a descrição na primeira linha (até linha em branco)
- [ ]  phpunit: Verificar se tem @return
- [ ] phpunit: Verificar se não tem tab
- [ ] phpunit: verificar espaçamento múltiplo de 4
